// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpReApqnGuiKg0G5YMn76AaDxKWADM_50',
    appId: '1:69177756351:web:f8322d1984f15b9f0f540a',
    messagingSenderId: '69177756351',
    projectId: 'flutter-softdev-uas',
    authDomain: 'flutter-softdev-uas.firebaseapp.com',
    storageBucket: 'flutter-softdev-uas.appspot.com',
    measurementId: 'G-Q8Z2NLD9KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6jQRl7i4FC7P33gbooZQmV_UakeFgWI',
    appId: '1:69177756351:android:768e73e0c6df7f0d0f540a',
    messagingSenderId: '69177756351',
    projectId: 'flutter-softdev-uas',
    storageBucket: 'flutter-softdev-uas.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDXvwRs2PWl-kUGadB3XbisA506G5JJRKo',
  //   appId: '1:69177756351:ios:2f850ec2e4f5058c0f540a',
  //   messagingSenderId: '69177756351',
  //   projectId: 'flutter-softdev-uas',
  //   storageBucket: 'flutter-softdev-uas.appspot.com',
  //   iosBundleId: 'com.example.flutterProject1',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDXvwRs2PWl-kUGadB3XbisA506G5JJRKo',
  //   appId: '1:69177756351:ios:2f850ec2e4f5058c0f540a',
  //   messagingSenderId: '69177756351',
  //   projectId: 'flutter-softdev-uas',
  //   storageBucket: 'flutter-softdev-uas.appspot.com',
  //   iosBundleId: 'com.example.flutterProject1',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyCpReApqnGuiKg0G5YMn76AaDxKWADM_50',
  //   appId: '1:69177756351:web:001c41f9e3a992060f540a',
  //   messagingSenderId: '69177756351',
  //   projectId: 'flutter-softdev-uas',
  //   authDomain: 'flutter-softdev-uas.firebaseapp.com',
  //   storageBucket: 'flutter-softdev-uas.appspot.com',
  //   measurementId: 'G-NW7F748XLB',
  // );
}
